using System;
using Xunit;

namespace NextGenSoftware.Holochain.HoloNET.Client.Tests;

public sealed class ManagedZomeCallSigningTests
{
    // Generated by dnas/oasis/zomes/coordinator/oasis/examples/signing_vector.rs using
    // holochain_zome_types 0.7.0 ZomeCallParams::serialize_and_hash().
    private const string ExpectedBytes = "88aa70726f76656e616e6365c4278420240102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f2000000000a763656c6c5f696492c427842d24292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40414243444546474800000000c4278420245152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f7000000000a97a6f6d655f6e616d65a56f61736973a7666e5f6e616d65b96170706c795f687970657264726976655f6d75746174696f6eaa6361705f736563726574c44079797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979797979a77061796c6f6164c44905060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4da56e6f6e6365c4204d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4daa657870697265735f6174cf000645a6b1321100";
    private const string ExpectedHash = "dcb55e6ed6b2ea8153faddd9b4f24232f6f29f698459ac3e4156c063ff6df4c8746aa7ade47046f7d101da85d1472f648325d72e7aa06f74cb107656cb563bf8";

    [Fact]
    public void ManagedSerializationAndHash_MatchHolochain07RustReference()
    {
        var call = CreateReferenceCall();
        var hash = new byte[HolochainSerialisationWrapper.DataToSignLength];
        var serialized = HolochainSerialisationWrapper.serialize_for_signing(call);

        HolochainSerialisationWrapper.call_get_data_to_sign(hash, call);

        Assert.Equal(ExpectedBytes, Convert.ToHexString(serialized).ToLowerInvariant());
        Assert.Equal(ExpectedHash, Convert.ToHexString(hash).ToLowerInvariant());
    }

    [Fact]
    public void DataToSign_RejectsLegacy32ByteDigestBuffer()
    {
        var error = Assert.Throws<ArgumentException>(() =>
            HolochainSerialisationWrapper.call_get_data_to_sign(new byte[32], CreateReferenceCall()));
        Assert.Contains("64 bytes", error.Message);
    }

    private static ZomeCallUnsigned CreateReferenceCall() => new()
    {
        // HoloHash::from_raw_39 normalizes the three-byte type prefix and checksum. These
        // are the exact wire bytes emitted by the Rust reference, as returned by a conductor.
        provenance = Hex("8420240102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f2000000000"),
        cell_id_dna_hash = Hex("842d24292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40414243444546474800000000"),
        cell_id_agent_pub_key = Hex("8420245152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f7000000000"),
        zome_name = "oasis",
        fn_name = "apply_hyperdrive_mutation",
        cap_secret = Repeated(64, 121),
        payload = Sequence(73, 5),
        nonce = Repeated(32, 77),
        expires_at = 1_765_432_100_000_000
    };

    private static byte[] Sequence(int length, int start)
    {
        var bytes = new byte[length];
        for (var i = 0; i < length; i++) bytes[i] = unchecked((byte)(start + i));
        return bytes;
    }

    private static byte[] Repeated(int length, byte value)
    {
        var bytes = new byte[length];
        Array.Fill(bytes, value);
        return bytes;
    }

    private static byte[] Hex(string value) => Convert.FromHexString(value);
}
